### ISSUE TITLE
CCH chart  adding erroneous lines

### ISSUE THREAD

**Issue by abbse** [gisce/empowering.js#1]
See attached screenshot
![captura_bug_cch](https://cloud.githubusercontent.com/assets/11310290/10245049/61da516e-6904-11e5-98ff-973a9ecee2cf.PNG)

**Comment by ecarreras** [comment]
I need the JSON of the data

**Comment by abbse** [comment]
JSON received data is not datetime sorted. Looks like has something to do with order of datetime points.

**Comment by ecarreras** [comment]
Maybe is an issue of [HeMan](https://github.com/gisce/heman/blob/master/heman/api/cch/__init__.py#L46) querying data, we have to sort the query of results

**Comment by ecarreras** [comment]
This https://github.com/gisce/heman/commit/efdbd912aa53cf7b4417f061e35bc7e21fa1485a should fix it.
